# Generated by Django 6.0.3 on 2026-03-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_menulist_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avl_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
