# Generated by Django 6.0.3 on 2026-04-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_product_avl_quantity_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iamge',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
