# Generated by Django 6.0.3 on 2026-04-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_product_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iamge',
            new_name='image',
        ),
    ]
