# Generated by Django 6.0 on 2026-04-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_productmaincategory_productsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
